#配置数据源
spring:
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:mysql://192.168.56.10:3306/moyu_mall?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: root
      password: root

      # 初始化配置
      initial-size: 3
      # 最小连接数
      min-idle: 3
      # 最大连接数
      max-active: 15
      # 获取连接超时时间
      max-wait: 5000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 90000
      # 最大空闲时间
      min-evictable-idle-time-millis: 1800000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

      validation-query: select 1
      # 配置监控统计拦截的filters
      filters: stat
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"

  #配置jpa
  jpa:
    hibernate:
      # 生产环境设置成 none，避免程序运行时自动更新数据库结构
      ddl-auto: update
  redis:
    #数据库索引
    database: 0
    host: 192.168.56.10
    port: 6379
    password:
    #链接超时时间
    timeout: 5000

  elasticsearch:
    rest:
      uris: http://192.168.56.10:9200

#jwt
jwt:
  header: Authorization
  #在线用户key
  online-key: xueden-online-token
  #令牌前缀
  token-start-with: Bearer
  #对令牌进行编码，必须使用最少88位的BASE64
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  #令牌过期时间，单位毫秒，默认4小时
  token-validity-in-seconds: 14400000
  #验证码
  code-key: xueden-code-key

#是否开启 swagger-ui
swagger:
  enabled: true

# 文件存储路径
file:
  path: G:\xuedenboot-vue\file\
  avatar: G:\xuedenboot-vue\avatar\
  # 文件大小 /M
  maxSize: 100
  avatarMaxSize: 5